### ISSUE TITLE
qBittorrent has dropped support for python2 since version 4.2.2

### ISSUE THREAD

**Issue by axzxc1236** [poplite/qBEE-Ubuntu-Packaging#1]
Under the [qBittorrent change log](https://www.qbittorrent.org/news.php) version 4.2.2 it says "SEARCH: Drop python2 support (Chocobo1)"  
[Another proof that current version of qBittorrent doesn't use python 2](https://github.com/qbittorrent/qBittorrent/issues/13227#issuecomment-667889556).

But the package from qBittorrent enhanced PPA still requires python2, it should be updated to depend on python3 (version later than 3.3.0, according to [download page](https://www.qbittorrent.org/download.php))

**Comment by poplite** [comment]
Thanks for reporting this issue! 

I have [updated](https://github.com/poplite/qBEE-Ubuntu-Packaging/commit/32ee8836eeef94f796e57e401a7652ce31e47ff8) the `debian/control` file and python2 is no longer required by the `qbittorrent-enhanced` package. 

With new `debian` context, the packages built for new release of qBEE on Launchpad should only depend on python3.
